"""initial schema

Revision ID: bee81bac70cc
Revises:
Create Date: 2026-08-23 16:02:46.928234
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "bee81bac70cc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("admin", "client", name="stationrole", native_enum=False), nullable=True
        ),
        sa.Column("required_closed", sa.Boolean(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("blocking", "warning", name="ruleseverity", native_enum=False),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("persistent_policy", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_rules")),
    )
    op.create_index(
        "ix_process_rules_enabled_role", "process_rules", ["enabled", "role"], unique=False
    )
    op.create_table(
        "publish_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("game_name", sa.String(length=255), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("allow_hot_switch", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("step", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "preflight",
                "awaiting_confirmation",
                "publishing",
                "switching",
                "verifying",
                "completed",
                "partial_failure",
                "failed",
                name="publishjobstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("operator_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("master_version_id", sa.Uuid(), nullable=True),
        sa.Column("client_confirmation", sa.Boolean(), nullable=True),
        sa.Column("client_confirmation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publish_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_publish_jobs_idempotency_key")),
    )
    op.create_index(
        "ix_publish_jobs_status_created", "publish_jobs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "client", name="stationrole", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "online", "stale", "offline", "disabled", name="stationstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("desired_version_id", sa.Uuid(), nullable=True),
        sa.Column("state_reason", sa.String(length=500), nullable=True),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("target_iqn", sa.String(length=255), nullable=True),
        sa.Column("initiator_iqn", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(enabled AND state <> 'disabled') OR (NOT enabled AND state = 'disabled')",
            name=op.f("ck_stations_enabled_state_consistent"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
        sa.UniqueConstraint("station_id", name=op.f("uq_stations_station_id")),
    )
    op.create_index("ix_stations_enabled_state", "stations", ["enabled", "state"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("agent_uuid", sa.Uuid(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("credential_hash", sa.String(length=255), nullable=True),
        sa.Column("credential_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_process_snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_drive_snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ip_addresses", sa.JSON(), nullable=False),
        sa.Column("last_mac_addresses", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_agents_station_id_stations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("agent_uuid", name=op.f("uq_agents_agent_uuid")),
        sa.UniqueConstraint("station_id", name=op.f("uq_agents_station_id")),
    )
    op.create_index("ix_agents_last_seen_at", "agents", ["last_seen_at"], unique=False)
    op.create_table(
        "enrollment_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_enrollment_tokens_station_id_stations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_enrollment_tokens_token_hash")),
    )
    op.create_index(
        "ix_enrollment_tokens_expires_at", "enrollment_tokens", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "dispatched", "failed", name="outboxeventstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["aggregate_id"],
            ["publish_jobs.id"],
            name=op.f("fk_outbox_events_aggregate_id_publish_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_pending", "outbox_events", ["status", "available_at"], unique=False
    )
    op.create_table(
        "process_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processes", sa.JSON(), nullable=False),
        sa.Column("drives", sa.JSON(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("freshness_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_process_snapshots_station_id_stations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_snapshots")),
    )
    op.create_index(
        "ix_process_snapshots_station_captured",
        "process_snapshots",
        ["station_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "publish_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deselected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preflight_status", sa.String(length=32), nullable=True),
        sa.Column("preflight_result", sa.JSON(), nullable=True),
        sa.Column("old_version_id", sa.Uuid(), nullable=True),
        sa.Column("new_version_id", sa.Uuid(), nullable=True),
        sa.Column("old_mapping", sa.JSON(), nullable=True),
        sa.Column("new_mapping", sa.JSON(), nullable=True),
        sa.Column("switch_status", sa.String(length=32), nullable=True),
        sa.Column("verify_status", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("progress_percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["publish_jobs.id"],
            name=op.f("fk_publish_targets_job_id_publish_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_publish_targets_station_id_stations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publish_targets")),
        sa.UniqueConstraint("job_id", "station_id", name="uq_publish_targets_job_station"),
    )
    op.create_index(
        "ix_publish_targets_job_switch",
        "publish_targets",
        ["job_id", "switch_status"],
        unique=False,
    )
    op.create_table(
        "agent_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signature", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_commands_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_commands")),
    )
    op.create_index(
        "ix_agent_commands_agent_status",
        "agent_commands",
        ["agent_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_agent_commands_lease_until", "agent_commands", ["lease_until"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_commands_lease_until", table_name="agent_commands")
    op.drop_index("ix_agent_commands_agent_status", table_name="agent_commands")
    op.drop_table("agent_commands")
    op.drop_index("ix_publish_targets_job_switch", table_name="publish_targets")
    op.drop_table("publish_targets")
    op.drop_index("ix_process_snapshots_station_captured", table_name="process_snapshots")
    op.drop_table("process_snapshots")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_enrollment_tokens_expires_at", table_name="enrollment_tokens")
    op.drop_table("enrollment_tokens")
    op.drop_index("ix_agents_last_seen_at", table_name="agents")
    op.drop_table("agents")
    op.drop_index("ix_stations_enabled_state", table_name="stations")
    op.drop_table("stations")
    op.drop_index("ix_publish_jobs_status_created", table_name="publish_jobs")
    op.drop_table("publish_jobs")
    op.drop_index("ix_process_rules_enabled_role", table_name="process_rules")
    op.drop_table("process_rules")
    # ### end Alembic commands ###
